### ISSUE TITLE
TypeError: add_weight() got multiple values for argument 'name'

### ISSUE THREAD

**Issue by rahmanjalayer** [Hsankesara/DeepResearch#9]
When I execute run_hun.py, it throws following error:

```
2020-11-04 16:53:37.555288: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'cudart64_101.dll'; dlerror: cudart64_101.dll not found
2020-11-04 16:53:37.555502: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
C:\Users\Rahman\PycharmProjects\hierarchialAttention\venv\lib\site-packages\pandas\core\generic.py:5168: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[name] = value
Total 74128 unique tokens.
Shape of data tensor: (124989, 4, 150)
Shape of labels tensor: (124989, 30)
Number of positive and negative reviews in traing and validation set
['ARTS', 'ARTS & CULTURE', 'BLACK VOICES', 'BUSINESS', 'COLLEGE', 'COMEDY', 'CRIME', 'EDUCATION', 'ENTERTAINMENT', 'FIFTY', 'GOOD NEWS', 'GREEN', 'HEALTHY LIVING', 'IMPACT', 'LATINO VOICES', 'MEDIA', 'PARENTS', 'POLITICS', 'QUEER VOICES', 'RELIGION', 'SCIENCE', 'SPORTS', 'STYLE', 'TASTE', 'TECH', 'TRAVEL', 'WEIRD NEWS', 'WOMEN', 'WORLD NEWS', 'WORLDPOST']
[1228, 1073, 3121, 3402, 932, 3207, 2317, 792, 11426, 1122, 1141, 2102, 5352, 2052, 929, 2246, 3132, 26136, 3991, 2069, 1097, 3295, 1797, 1693, 985, 1727, 2108, 2780, 1747, 4993]
[281, 266, 737, 852, 212, 764, 576, 212, 2831, 279, 257, 520, 1342, 550, 200, 569, 823, 6603, 1004, 487, 284, 872, 457, 403, 246, 418, 562, 710, 430, 1250]
Total absent words are 17810 which is 24.03 % of total words
2020-11-04 16:54:21.322906: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'nvcuda.dll'; dlerror: nvcuda.dll not found
2020-11-04 16:54:21.323104: W tensorflow/stream_executor/cuda/cuda_driver.cc:312] failed call to cuInit: UNKNOWN ERROR (303)
2020-11-04 16:54:21.326789: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:169] retrieving CUDA diagnostic information for host: DESKTOP-MMSO9D8
2020-11-04 16:54:21.327043: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:176] hostname: DESKTOP-MMSO9D8
2020-11-04 16:54:21.336196: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x179cfa0ad80 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-11-04 16:54:21.336432: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
Traceback (most recent call last):
  File "C:/Users/Rahman/PycharmProjects/hierarchialAttention/run_han.py", line 42, in <module>
    main()
  File "C:/Users/Rahman/PycharmProjects/hierarchialAttention/run_han.py", line 28, in main
    max_senten_len=150, max_senten_num=4, embedding_size=100, validation_split=0.2, verbose=1)
  File "C:\Users\Rahman\PycharmProjects\hierarchialAttention\HAN.py", line 74, in __init__
    self.set_model()
  File "C:\Users\Rahman\PycharmProjects\hierarchialAttention\HAN.py", line 241, in set_model
    word_att = AttentionWithContext()(word_dense)
  File "C:\Users\Rahman\PycharmProjects\hierarchialAttention\venv\lib\site-packages\tensorflow\python\keras\engine\base_layer.py", line 926, in __call__
    input_list)
  File "C:\Users\Rahman\PycharmProjects\hierarchialAttention\venv\lib\site-packages\tensorflow\python\keras\engine\base_layer.py", line 1098, in _functional_construction_call
    self._maybe_build(inputs)
  File "C:\Users\Rahman\PycharmProjects\hierarchialAttention\venv\lib\site-packages\tensorflow\python\keras\engine\base_layer.py", line 2643, in _maybe_build
    self.build(input_shapes)  # pylint:disable=not-callable
  File "C:\Users\Rahman\PycharmProjects\hierarchialAttention\attention_with_context.py", line 72, in build
    constraint=self.W_constraint)
TypeError: add_weight() got multiple values for argument 'name'
```

**Comment by mertayD** [comment]
I had the same issue as well!

**Comment by miryamelizabeth** [comment]
same issue! :(
